# Generated by Django 4.2.4 on 2023-12-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_feedbackbox_email_alter_feedbackbox_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Username', models.CharField(max_length=255, null=True)),
                ('Password', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedbackbox',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
