# Generated by Django 4.2.4 on 2024-01-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_userform_alter_feedbackbox_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
