# Generated by Django 4.2.4 on 2024-01-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_delete_userform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedbackbox',
        ),
    ]
